image: alpine:latest

before_script: |
  apk update
  apk add git wget npm python3 py3-pip
  npm install -g tiddlywiki
  pip3 install beautifulsoup4 html5lib

pages:
  stage: deploy
  script: |
    ash ./Bootstrap.sh
    ash ./Deploy.CrossRepoSync.sh
  artifacts:
    paths:
    - public
